package wsdl.cxf.tutorial.generatedskliton;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-20T02:09:47.794+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "UserServicesService", 
                  wsdlLocation = "file:/E:/EclipseKeplerProject/tutorial.cxf.wsdl2java/src/main/resources/wsdl/UserServices.wsdl",
                  targetNamespace = "http://tutorial.cxf.wsdl/v1") 
public class UserServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tutorial.cxf.wsdl/v1", "UserServicesService");
    public final static QName UserServicesPort = new QName("http://tutorial.cxf.wsdl/v1", "UserServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/EclipseKeplerProject/tutorial.cxf.wsdl2java/src/main/resources/wsdl/UserServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/EclipseKeplerProject/tutorial.cxf.wsdl2java/src/main/resources/wsdl/UserServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns UserServices
     */
    @WebEndpoint(name = "UserServicesPort")
    public UserServices getUserServicesPort() {
        return super.getPort(UserServicesPort, UserServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServices
     */
    @WebEndpoint(name = "UserServicesPort")
    public UserServices getUserServicesPort(WebServiceFeature... features) {
        return super.getPort(UserServicesPort, UserServices.class, features);
    }

}
