package wsdl.cxf.tutorial.generatedskliton;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-20T02:09:47.722+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://tutorial.cxf.wsdl/v1", name = "UserServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserServices {

    @WebResult(name = "getUserResponse", targetNamespace = "http://tutorial.cxf.wsdl/v1", partName = "parameters")
    @WebMethod
    public User getUser(
        @WebParam(partName = "parameters", name = "getUser", targetNamespace = "http://tutorial.cxf.wsdl/v1")
        java.lang.String parameters
    ) throws UserNotFoundException;
}
