
package wsdl.cxf.tutorial.generatedskliton;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-20T02:09:47.591+05:30
 * Generated source version: 3.0.1
 */

@WebFault(name = "UserNotFoundException", targetNamespace = "http://tutorial.cxf.wsdl/v1")
public class UserNotFoundException extends Exception {
    
    private wsdl.cxf.tutorial.generatedskliton.CheckFaultBean userNotFoundException;

    public UserNotFoundException() {
        super();
    }
    
    public UserNotFoundException(String message) {
        super(message);
    }
    
    public UserNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public UserNotFoundException(String message, wsdl.cxf.tutorial.generatedskliton.CheckFaultBean userNotFoundException) {
        super(message);
        this.userNotFoundException = userNotFoundException;
    }

    public UserNotFoundException(String message, wsdl.cxf.tutorial.generatedskliton.CheckFaultBean userNotFoundException, Throwable cause) {
        super(message, cause);
        this.userNotFoundException = userNotFoundException;
    }

    public wsdl.cxf.tutorial.generatedskliton.CheckFaultBean getFaultInfo() {
        return this.userNotFoundException;
    }
}
